### ISSUE TITLE
Words with multiple of the same letter print "That's correct!" twice when guessed correctly

### ISSUE THREAD

**Issue by ncarmine** [mdenardis/DeNardis_CSCI2270_FinalProject#6]
If a word has the same letter in it twice ("state", "arrow", etc) it will print "That's correct!" followed by the word twice. For instance, if the word is "arrow" and you guess 'r':

`Guess: r`
`That's correct! a r _ _ _`

`That's correct! a r r _ _`

This will require reworking the if statement and for loop that checks in the letter is correct in Hangman::hangmanGame().

**Comment by T33R0** [comment]
Roget that. We acknowledge that as an issue. Thanks for the feedback.
